---
- name: Set application directory
  set_fact:
    bamboo_application_directory: "{{ bamboo_root_directory }}/atlassian-bamboo-{{ bamboo_version }}"

- name: "Install JDK"
  yum:
    name: "java-{{ openjdk_version }}-openjdk"
    state: installed

- name: Add local user
  user:
    name: "{{ bamboo_user }}"

- name: Create app and data folders
  file:
    name: "{{ item }}"
    state: directory
    owner: "{{ bamboo_user }}"
    group: "{{ bamboo_user }}"
  with_items:
    - "{{ bamboo_home_directory }}"
    - "{{ bamboo_root_directory }}"

- name: Check for downgrade
  fail: msg="Downgrades are not supported. Please set bamboo_version to higher or equal to {{ ansible_local.bamboo.version }}. Current value is {{ bamboo_version }}"
  when:
    - ansible_local is defined
    - ansible_local.bamboo is defined
    - ansible_local.bamboo.version is defined
    - bamboo_version | version_compare(ansible_local.bamboo.version, '<')

- name: Stop when upgrade
  systemd:
    name: bamboo
    state: stopped
  when:
    - ansible_local is defined
    - ansible_local.bamboo is defined
    - ansible_local.bamboo.version is defined
    - bamboo_version | version_compare(ansible_local.bamboo.version, '>')
  notify: restart bamboo

- name: Download and unpack bamboo
  unarchive:
    src: "https://www.atlassian.com/software/bamboo/downloads/binary/atlassian-bamboo-{{ bamboo_version }}.tar.gz"
    dest: "{{ bamboo_root_directory }}"
    remote_src: True
    # keep our modified, newer files instead of overriding from the tarball
    keep_newer: yes
  changed_when: False

- name: Configure bamboo server (server.xml)
  template:
    src: server.xml.j2
    dest: "{{ bamboo_application_directory }}/conf/server.xml"
  notify: restart bamboo

- name: Copy logrotate script for syslog
  copy:
    src: syslog
    dest: /etc/logrotate.d/syslog

- name: Add cronjob for cleanup Bamboo logs
  cron:
    name: cleanupbamboologs
    special_time: daily
    state: present
    job: "/usr/bin/find {{ bamboo_application_directory }}/logs/ -name *.log -type f -mtime +7 -exec rm  {} \\;"

- name: Add cronjob for cleanup Bamboo build-dir
  cron:
    name: cleanupbamboobuilddir
    hour: 03
    minute: 15
    weekday: 0 # sunday
    state: present
    job: "/usr/bin/find {{ bamboo_home_directory }}/xml-data/build-dir/ -maxdepth 1 -type d -mtime +1 -exec rm -rf {} \\;"

- name: Add cronjob for cleanup maven repository cache
  cron:
    name: cleanupbamboomavenrepo
    hour: 03
    minute: 15
    weekday: 0 # sunday
    state: present
    job: "/usr/bin/find {{ bamboo_home_directory }}/.m2/repository/ -maxdepth 1 -type d -mtime +1 -exec rm -rf {} \\;"

- name: Install bamboo systemd unit script
  template:
    src: bamboo.service.j2
    dest: /etc/systemd/system/bamboo.service
    mode: 0744
  notify: restart bamboo

- name: Set bamboo.home property variable
  template:
    src: bamboo-init.properties
    dest: "{{ bamboo_application_directory }}/atlassian-bamboo/WEB-INF/classes/bamboo-init.properties"
  notify: restart bamboo

- name: Set JVM settings
  replace:
    dest: "{{ bamboo_application_directory }}/bin/setenv.sh"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - regexp: 'JVM_MINIMUM_MEMORY="[0-9]+[bkmg]'
      replace: 'JVM_MINIMUM_MEMORY="{{ bamboo_jvm_heap_min }}'
    - regexp: 'JVM_MAXIMUM_MEMORY="[0-9]+[bkmg]'
      replace: 'JVM_MAXIMUM_MEMORY="{{ bamboo_jvm_heap_max }}'
  notify: restart bamboo

- name: Fix permissions on application folder
  file:
    path: "{{ item }}"
    recurse: yes
    owner: "{{ bamboo_user }}"
    group: "{{ bamboo_user }}"
  changed_when: False
  with_items:
    - "{{ bamboo_application_directory }}"

- name: Ensure ansible facts folder exists
  file:
    name: /etc/ansible/facts.d/
    state: directory
    recurse: yes

- name: Ensure bamboo facts exists
  file:
    name: /etc/ansible/facts.d/bamboo.fact
    state: touch
  changed_when: False

- name: Update bamboo facts
  template:
    src: bamboo.fact.j2
    dest: /etc/ansible/facts.d/bamboo.fact
  notify: restart bamboo
