- debug:
    msg: "Some mimacom.bamboo role vars you are using are deprecated. Please consult README."

- name: Set bamboo_master_version
  set_fact:
    bamboo_master_version: "{{ bamboo_master.version }}"
  when: bamboo_master.version is defined

- name: Set bamboo_master_fqdn
  set_fact:
    bamboo_master_fqdn: "{{ bamboo_master.fqdn }}"
  when: bamboo_master.fqdn is defined

- name: Set bamboo_master_https
  set_fact:
    bamboo_master_https: "{{ bamboo_master.https }}"
  when: bamboo_master.https is defined

- name: Set bamboo_master_port
  set_fact:
    bamboo_master_port: "{{ bamboo_master.port }}"
  when: bamboo_master.port is defined

  - name: Set bamboo_master_include_jdk
  set_fact:
    bamboo_master_include_jdk: "{{ bamboo_include_jdk }}"
  when: bamboo_include_jdk is defined

  - name: Set bamboo_master_openjdk_version
  set_fact:
    bamboo_master_openjdk_version: "{{ openjdk_version }}"
  when: openjdk_version is defined
