- name: Install python-lxml for ansible xml module
  package:
    name: python-lxml

- name: Set tomcat connector proxyName in server.xml
  xml:
    path: "{{ bamboo_master_binary_folder }}/conf/server.xml"
    xpath: /Server/Service/Connector
    attribute: proxyName
    value: "{{ bamboo_master_fqdn }}"
  when: bamboo_master_fqdn is defined
  notify: restart bamboo

- name: Set tomcat connector proxyPort server.xml
  xml:
    path: "{{ bamboo_master_binary_folder }}/conf/server.xml"
    xpath: /Server/Service/Connector
    attribute: proxyPort
    value: "{{ bamboo_master_port }}"
  when: bamboo_master_port is defined
  notify: restart bamboo

- name: Set tomcat connector scheme server.xml
  xml:
    path: "{{ bamboo_master_binary_folder }}/conf/server.xml"
    xpath: /Server/Service/Connector
    attribute: scheme
    value: "https"
  when:
    - bamboo_master_https is defined
    - bamboo_master_https
  notify: restart bamboo
